version: '3.4'

services:
  traefik:
    image: traefik:v2.9
    volumes:
      - '$PWD/traefik.toml:/traefik.toml'
      - '$PWD/traefik_dynamic.toml:/traefik_dynamic.toml'
      - '$PWD/acme.json:/acme.json'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '80:80'
      - '443:443'
    network_mode: host
    container_name: traefik
